### ISSUE TITLE
Investigate possible problems in "About Reflectance Recovery - Smits (1999) Method" notebook

### ISSUE THREAD

**Issue by henczati** [colour-science/colour-website#1]
At the time of creating this issue, [this is the latest version of the notebook](../blob/f9b603b46c0ffeeab7d7ffdb90ba544f82355346/ipython/about_reflectance_recovery.ipynb).

This issue is meant to focus on the code in the notebook itself, while colour-science/colour#196 (presumably) on the underlying core functions used in the notebook.
### Initial motivation

@KelSolaar's note in the notebook suggests that the differences in colour between the rendered outputs of the reference and the recovered spectra seem to be higher than (intuitively) expected.

**Comment by henczati** [comment]
Some preliminary observations:
- `mean_r` defined @ `In [2]:32` is never used/read. What was the intention behind putting it in? (Dropped feature/addition? Forgot to use it somewhere?)
- No `from __future__ import division` in the notebook. IIRC it is not inherited from imported modules into the notebooks environment. I noticed e.g. the XYZ scaling done by `/ 100` and not by `/ 100.`. This is probably not causing any trouble here specifically, as the computed XYZ values should already be floats. Still, I thought I mention it, just to be safe (I currently use Python 2.7, and in a fresh environment `5/3` is still `1` there). Could there be some other place/computation where this might be a problem?

**Comment by thomasmansencal** [comment]
- `mean_r` is probably a left over of when I was trying to investigate for the discrepancies, I don't remember its exact purpose but it should not be there.
- `from __future__ import division` shouldn't matter yeah :)

One axis of investigation I will start with is entirely discard chromatic adaptation and see if it can from here.

**Comment by thomasmansencal** [comment]
Brian's restored code unfortunately doesn't produce his papers values thus making it quite hard to find what's exactly is going on. I'll close that issue for now.
